<?php

########################################################################
# Extension Manager/Repository config file for ext: "podcast"
#
# Auto generated by Extension Builder 2012-01-25
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Podcast',
	'description' => 'Handel multiple Podcasts.',
	'category' => 'plugin',
	'author' => 'Noël Bossart',
	'author_email' => 'n dot company at me dot com',
	'author_company' => 'noelboss.ch',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.3.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>